### ISSUE TITLE
concat and minifiy all css and js 

### ISSUE THREAD

**Issue by butlerx** [redbrick/hexo-theme-icarus#22]
- [ ] concat and all the css not in the stylus files in to one file for minification
- [ ] concat all the js files in to one file for import

Gulp would be best for this
the stylus files can be ignored as that's taken care of by hexo

**Comment by vijay-raghav** [comment]
Hi! I'm interested in doing this. I understand the minify JS part but not the CSS part - could you please explain this?

> concat and all the css not in the stylus files in to one file for minification

**Comment by butlerx** [comment]
so if you look [here](https://github.com/redbrick/hexo-theme-icarus/blob/master/layout/common/head.ejs#L40) and [here](https://github.com/redbrick/hexo-theme-icarus/blob/master/layout/plugin/scripts.ejs#L3) youll see we import a few css files these files all need to be concated and minfied so we only import one css file
