### ISSUE TITLE
move to vendor folder to bower_components and delete folder after concatination

### ISSUE THREAD

**Issue by butlerx** [redbrick/hexo-theme-icarus#34]
gulp del can delete the folder after it builds the dep should make deployment shorter

**Comment by idmarjr** [comment]
Hi @butlerx !
Can you gimme a bit more of context about this?

I'm assuming that this issue is not valid anymore since you moved from bower to npm here:
https://github.com/redbrick/hexo-theme-icarus/commit/7df4d111eb0e1038a10d716edc63c884900eb405

**Comment by butlerx** [comment]
oh very true no longer needed
